name: todo
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  cupertino_icons: ^1.0.8
  material_color_utilities: ^0.11.1
  async: ^2.12.0
  fake_async: ^1.3.2
  leak_tracker: ^10.0.8
  vm_service: ^14.3.1 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo1.png"

flutter:
  assets:
    - assets/logo1.png
  uses-material-design: true